export default {
    items: {
        ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
        entities: {
            0: {
                id: 0, 
				name: 'Fusili',
                category: 'Pasta',
                section: 'Pantry',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: false        
            },
            1: {
                id: 1, 
				name: 'Penne',
                category: 'Pasta',
                section: 'Pantry',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: true        
            },
            2: {
                id: 2, 
				name: 'Spaghetti',
                category: 'Pasta',
                section: 'Pantry',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: false        
            },
            3: {
                id: 3, 
				name: 'Baguette',
                category: 'Bread',
                section: 'Pantry',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: false        
            },
            4: {
                id: 4, 
				name: 'Pita',
                category: 'Bread',
                section: 'Pantry',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: false        
            },
            5: {
                id: 5, 
				name: 'Tortilla',
                category: 'Bread',
                section: 'Pantry',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: false        
            },
            6: {
                id: 6, 
				name: 'Apple',
                category: 'Fruit',
                section: 'Fresh',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: false        
            },
            7: {
                id: 7, 
				name: 'Pear',
                category: 'Fruit',
                section: 'Fresh',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: false        
            },
            8: {
                id: 8, 
				name: 'Grapes',
                category: 'Fruit',
                section: 'Fresh',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: false        
            },
            9: {
                id: 9, 
				name: 'Potato',
                category: 'Veggies',
                section: 'Fresh',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: false        
            },
            10: {
                id: 10, 
				name: 'Onion',
                category: 'Veggies',
                section: 'Fresh',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: false        
            },
            11: {
                id: 11, 
				name: 'Tomato',
                category: 'Veggies',
                section: 'Fresh',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: false        
            },
            12: {
                id: 12, 
				name: 'Mint Chocolate Chip',
                category: 'Ice Cream',
                section: 'Frozen',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: true        
            },
            13: {
                id: 13, 
				name: 'Vanilla',
                category: 'Ice Cream',
                section: 'Frozen',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: false        
            },
            14: {
                id: 14, 
				name: 'Cookie Dough',
                category: 'Ice Cream',
                section: 'Frozen',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: false        
            },
            15: {
                id: 15, 
				name: 'Okra',
                category: 'Veggies',
                section: 'Frozen',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: false        
            },
            16: {
                id: 16, 
				name: 'Peas',
                category: 'Veggies',
                section: 'Frozen',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: false        
            },
            17: {
                id: 17, 
				name: 'Corn',
                category: 'Veggies',
                section: 'Frozen',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: false        
            },
            18: {
                id: 18, 
				name: 'Vinegar',
                category: 'Solutions',
                section: 'Cleaning',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: false        
            },
            19: {
                id: 19, 
				name: 'Toilet Bowl Cleaner',
                category: 'Solutions',
                section: 'Cleaning',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: false        
            },
            20: {
                id: 20, 
				name: 'Sanitizer',
                category: 'Solutions',
                section: 'Cleaning',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: true        
            },
            21: {
                id: 21, 
				name: 'Paper Towels',
                category: 'Supplies',
                section: 'Cleaning',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: false        
            },
            22: {
                id: 22, 
				name: 'Toilet Paper',
                category: 'Supplies',
                section: 'Cleaning',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: false        
            },
            23: {
                id: 23, 
				name: 'Sponges',
                category: 'Supplies',
                section: 'Cleaning',
                currentQuantity: 10,
                desiredQuantity: 42,
                price: '1.52',
                expirationDate: '10/12/2021',
                formattedDate: '2021-10-12',
                onShoppingList: false        
            },
        }
        // allNames: [ "Fusili", "Penne", "Spaghetti", "Baguette", "Pita", "Tortilla", "Apple",
        //     "Pear", "Grapes", "Potato", "Onion", "Tomato", "Mint Chocolate Chip", "Vanilla",
        //     "Cookie Dough", "Okra", "Peas", "Corn", "Vinegar", "Toilet Bowl Cleaner", "Sanitizer",
        //     "Paper Towels", "Toilet Paper", "Sponges" ]
    },
    categories: {
        ids: [ 0, 1, 2, 3, 4, 5, 6 ],
        entities: {
            0: {id: 0, name: 'Pasta'},
            1: {id: 1, name: 'Bread'},
            2: {id: 2, name: 'Fruit'},
            3: {id: 3, name: 'Veggies'},
            4: {id: 4, name: 'Ice Cream'},
            5: {id: 5, name: 'Solutions'},
            6: {id: 6, name: 'Supplies'}
        }
    },
    sections: {
        ids: [ 0, 1, 2, 3, 4 ],
        entities: {
            0: {id: 0, name: 'All'},
            1: {id: 1, name: 'Pantry'},
            2: {id: 2, name: 'Fresh'},
            3: {id: 3, name: 'Frozen'},
            4: {id: 4, name: 'Cleaning'}
        },
    }
}